%% 辅助函数: 获取默认电极配置
function chanSet = getDefaultChannelSet(numChans)
% 获取预设电极配置
switch numChans
    case 28
        % 28 导联 (PLC 常用)
        chanSet = {'FC5','FC3','FC1','FCZ','FC2','FC4','FC6',...
                  'C5','C3','C1','CZ','C2','C4','C6',...
                  'CP5','CP3','CP1','CPZ','CP2','CP4','CP6',...
                  'P5','P3','P1','PZ','P2','P4','P6'};
    case 60
        % 60 导联 (全脑区)
        chanSet = {'FP1','FPZ','FP2','AF3','AF4',...
                  'F7','F5','F3','F1','FZ','F2','F4','F6','F8',...
                  'FT7','FC5','FC3','FC1','FCZ','FC2','FC4','FC6','FT8',...
                  'T7','C5','C3','C1','CZ','C2','C4','C6','T8',...
                  'TP7','CP5','CP3','CP1','CPZ','CP2','CP4','CP6','TP8',...
                  'P7','P5','P3','P1','PZ','P2','P4','P6','P8',...
                  'PO7','PO5','PO3','POZ','PO4','PO6','PO8',...
                  'O1','OZ','O2'};
    otherwise
        error('不支持的通道数: %d (支持 28 或 60 导联)', numChans);
end
end